//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebtMan.WebApp.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DebtManWebAppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DebtManWebAppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DebtMan.WebApp.App_GlobalResources.DebtManWebAppResources", typeof(DebtManWebAppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Owed.
        /// </summary>
        public static string CreditorRepaymentViewModelAmountOwedDisplayName {
            get {
                return ResourceManager.GetString("CreditorRepaymentViewModelAmountOwedDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Repayment.
        /// </summary>
        public static string CreditorRepaymentViewModelMonthlyRepaymentDisplayName {
            get {
                return ResourceManager.GetString("CreditorRepaymentViewModelMonthlyRepaymentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Owed.
        /// </summary>
        public static string DebtEditModelAmountOwedDisplayName {
            get {
                return ResourceManager.GetString("DebtEditModelAmountOwedDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string DebtorEditModelCompanyNameDisplayName {
            get {
                return ResourceManager.GetString("DebtorEditModelCompanyNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenditure.
        /// </summary>
        public static string DebtorEditModelExpenditureDisplayName {
            get {
                return ResourceManager.GetString("DebtorEditModelExpenditureDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string DebtorEditModelIncomeDisplayName {
            get {
                return ResourceManager.GetString("DebtorEditModelIncomeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DebtorEditModelNameDisplayName {
            get {
                return ResourceManager.GetString("DebtorEditModelNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string DebtorViewModelCompanyNameDisplayName {
            get {
                return ResourceManager.GetString("DebtorViewModelCompanyNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposable Income.
        /// </summary>
        public static string DebtorViewModelDisposableIncomeDisplayName {
            get {
                return ResourceManager.GetString("DebtorViewModelDisposableIncomeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenditure.
        /// </summary>
        public static string DebtorViewModelExpenditureDisplayName {
            get {
                return ResourceManager.GetString("DebtorViewModelExpenditureDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string DebtorViewModelIncomeDisplayName {
            get {
                return ResourceManager.GetString("DebtorViewModelIncomeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DebtorViewModelNameDisplayName {
            get {
                return ResourceManager.GetString("DebtorViewModelNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount Owed.
        /// </summary>
        public static string DebtorViewModelTotalAmountOwedDisplayName {
            get {
                return ResourceManager.GetString("DebtorViewModelTotalAmountOwedDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Owed.
        /// </summary>
        public static string DebtViewModelAmountOwedDisplayName {
            get {
                return ResourceManager.GetString("DebtViewModelAmountOwedDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string DMPViewModelCompanyNameDisplayName {
            get {
                return ResourceManager.GetString("DMPViewModelCompanyNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposable Income.
        /// </summary>
        public static string DMPViewModelDebtorDisposableIncomeDisplayName {
            get {
                return ResourceManager.GetString("DMPViewModelDebtorDisposableIncomeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenditure.
        /// </summary>
        public static string DMPViewModelDebtorExpenditureDisplayName {
            get {
                return ResourceManager.GetString("DMPViewModelDebtorExpenditureDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string DMPViewModelDebtorIncomeDisplayName {
            get {
                return ResourceManager.GetString("DMPViewModelDebtorIncomeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DMPViewModelDebtorNameDisplayName {
            get {
                return ResourceManager.GetString("DMPViewModelDebtorNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount Owed.
        /// </summary>
        public static string DMPViewModelDebtorTotalAmountOwedDisplayName {
            get {
                return ResourceManager.GetString("DMPViewModelDebtorTotalAmountOwedDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Management Fee.
        /// </summary>
        public static string DMPViewModelMonthlyManagementFeeDisplayName {
            get {
                return ResourceManager.GetString("DMPViewModelMonthlyManagementFeeDisplayName", resourceCulture);
            }
        }
    }
}
